### ISSUE TITLE
Duplicated 'description' key in sessions.yml for mobile__app_set_id_scope

### ISSUE THREAD

**Issue by pavaud** [snowplow/dbt-snowplow-unified#109]
## Describe the bug
The `models/sessions/sessions.yml` file include a duplicated `description` key for the `mobile__app_set_id_scope` column. It raises a deprecation warning in dbt Cloud.

```yaml
    - name: mobile__app_set_id_scope
        description: '{{ doc("col_app_set_id_scope") }}'
        description: '{{ doc("col_geo_country") }}'
```

The **col_geo_country** description should be removed.

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] databricks
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
1.10 in dbt Cloud
