### ISSUE TITLE
Users sessions is very slow to process

### ISSUE THREAD

**Issue by drphrozen** [snowplow/dbt-snowplow-unified#58]
## Describe the bug
In our dbt run of unified `snowplow_unified_users_sessions_this_run` takes 29742s out of 31658s (~94%).

## Steps to reproduce
In our case, add a lot of users and run unified model.

## Expected results
That the peformance matched web dbt :)

## Actual results
Its not

## Screenshots and log output
[dbt-output.txt](https://github.com/user-attachments/files/15865390/dbt-output.txt)

## System information
**The contents of your `packages.yml` file:**
```yml
# add dependencies. these will get pulled during the `dbt deps` process.
---
packages:
  # https://hub.getdbt.com/dbt-labs/dbt_utils/latest/
  - package: dbt-labs/dbt_utils
    version: [">=1.1.1", "<2.0.0"]

  - package: snowplow/snowplow_unified
    version: 0.4.0

  - package: snowplow/snowplow_ecommerce
    version: 0.8.2
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [ ] snowflake
- [x] databricks
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
1.8.2
```

**The operating system you're using:**
N/A

**The output of `python --version`:**
N/A

## Additional context
Compared to dbt web it looks like the calculation of start/end time was done incrementally, but is now calculated directly when needed.

## Are you interested in contributing towards the fix?
Yes, if feedback is needed
